version: "3.9"

services:

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    ports:
      - 50000:50000
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.jenkins.rule=Host(`jenkins.${BASE_DOMAIN}`)
      - traefik.http.routers.jenkins.entrypoints=websecure
      - traefik.http.routers.jenkins.tls.certresolver=myresolver
      - traefik.http.services.jenkins.loadbalancer.server.port=8080
      - traefik.docker.network=traefik


networks:
  traefik:
    external: true